version: "3.7"
services:
    web:
      image: registry.gitlab.com/1337its/projects/bkwire/dev-nginx:latest
      hostname: bkw-nginx
      restart: unless-stopped
      tty: true
      volumes:
        - nginx:/var/log/nginx/
      networks:
        - agent-network
        - traefik-public
      depends_on:
          - flaskapi
      command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      deploy:
        placement:
          constraints:
            - node.labels.bkwire-node-dev == true
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.web-http.rule=Host(`bkwire.1337itsolutions.com`, `www.bkwire.1337itsolutions.com`)
          - traefik.http.routers.web-http.entrypoints=http
          - traefik.http.routers.web-http.middlewares=https-redirect
          - traefik.http.routers.web-https.rule=Host(`bkwire.1337itsolutions.com`, `www.bkwire.1337itsolutions.com`)
          - traefik.http.routers.web-https.entrypoints=https
          - traefik.http.routers.web-https.tls=true
          - traefik.http.routers.web-https.tls.certresolver=le
          - traefik.http.services.web.loadbalancer.server.port=80
          
    flaskapi:
      image: registry.gitlab.com/1337its/projects/bkwire/dev-flask_api:latest
      hostname: bkw-flaskapi
      restart: unless-stopped
      ports:
        - 5000:5000
      tty: true
      volumes:
        - flaskapp:/app/logs
        - script_data:/script/data
      networks:
        - agent-network
        - traefik-public
      command: uwsgi --ini /app/uwsgi.ini
      deploy:
        placement:
          constraints:
            - node.labels.bkwire-node-dev == true
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.flaskapi-http.rule=Host(`flask-api.1337itsolutions.com`)
          - traefik.http.routers.flaskapi-http.entrypoints=http
          - traefik.http.routers.flaskapi-http.middlewares=https-redirect
          - traefik.http.routers.flaskapi-https.rule=Host(`flask-api.1337itsolutions.com`)
          - traefik.http.routers.flaskapi-https.entrypoints=https
          - traefik.http.routers.flaskapi-https.tls=true
          - traefik.http.routers.flaskapi-https.tls.certresolver=le
          - traefik.http.services.flaskapi.loadbalancer.server.port=5000

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      hostname: bkw-phpmyadmin
      restart: always
      networks:
        - agent-network
        - traefik-public
      deploy:
        placement:
          constraints:
            - node.labels.bkwire-node-dev == true
        labels:
          - traefik.enable=true
          - traefik.docker.network=traefik-public
          - traefik.constraint-label=traefik-public
          - traefik.http.routers.phpmyadmin-http.rule=Host(`phpmyadmin.1337itsolutions.com`)
          - traefik.http.routers.phpmyadmin-http.entrypoints=http
          - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

networks:
  agent-network:
    attachable: true
  traefik-public:
    external: true

volumes:
  db_data:
  script_data:
  flaskapp:
  nginx:
