version: "3.7"
services:
    web:
      image: registry.gitlab.com/1337its/projects/bkwire/local-nginx:latest
      ports:
        - "4200:80"
      volumes:
        - ./docker/nginx/conf.d/local.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    flaskapi:
      ports:
        - "8500:5000"
      env_file:
        - environment-vars.env
      volumes:
        - ./docker/flask_api:/app
        - ./docker/flask_api/logs:/app/logs

    phpmyadmin:
      ports:
        - "8306:80"
      environment:
        - UPLOAD_LIMIT=500M

    mysql:
      image: mysql/mysql-server

    hub:
      image: selenium/hub
      hostname: dev-bkw-hub
      ports:
        - "4444:4444"
      environment:
        GRID_MAX_SESSION: 16
        GRID_BROWSER_TIMEOUT: 3000
        GRID_TIMEOUT: 3000

    chrome:
      image: seleniarm/standalone-firefox:latest
      hostname: dev-bkw-chrome
      container_name: web-automation_chrome
      depends_on:
        - hub
      environment:
        SE_EVENT_BUS_HOST: hub
        SE_EVENT_BUS_PUBLISH_PORT: 4442
        SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
        SE_NODE_MAX_SESSIONS: 5
        SE_NODE_OVERRIDE_MAX_SESSIONS: 'false'
        SE_SHM_SIZE: '2g'
      volumes:
        - /dev/shm:/dev/shm
      ports:
        - "9001:5900"

