import {
  Fastfood,
  Computer,
  MiscellaneousServices,
  MedicalServices,
  AccountBalance,
  PrecisionManufacturing,
  Commute,
  CardTravel,
  Construction,
  Apartment,
  PointOfSale,
  Chair,
  FilePresent,
  Science,
  LocalGasStation,
  BusinessCenter,
  Checkroom,
  Factory,
} from '@mui/icons-material';
import { AmountRange, ChapterType } from './api.types';

export const TRIAL_DAYS = 14;

export const ranges: AmountRange[] = [
  { id: 1, min: 0, max: 50000 },
  { id: 2, min: 50001, max: 100000 },
  { id: 3, min: 100001, max: 500000 },
  { id: 4, min: 500001, max: 1000000 },
  { id: 5, min: 1000001, max: 10000000 },
  { id: 6, min: 10000001, max: 50000000 },
  { id: 7, min: 50000001, max: 100000000 },
  { id: 8, min: 100000001, max: 500000000 },
  { id: 9, min: 500000001, max: 1000000000 },
  { id: 10, min: 1000000001, max: -1000000000 },
];

export const chapterTypes: ChapterType[] = [
  { id: 7, name: '7 Liquidation' },
  { id: 11, name: '11 Reorganization' },
];

export const states: Record<string, string> = {
  '': 'Any state',
  AK: 'Alaska',
  AL: 'Alabama',
  AR: 'Arkansas',
  AZ: 'Arizona',
  CA: 'California',
  CO: 'Colorado',
  CT: 'Connecticut',
  DC: 'District of Columbia',
  DE: 'Delaware',
  FL: 'Florida',
  GA: 'Georgia',
  HI: 'Hawaii',
  IA: 'Iowa',
  ID: 'Idaho',
  IL: 'Illinois',
  IN: 'Indiana',
  KS: 'Kansas',
  KY: 'Kentucky',
  LA: 'Louisiana',
  MA: 'Massachusetts',
  MD: 'Maryland',
  ME: 'Maine',
  MI: 'Michigan',
  MN: 'Minnesota',
  MO: 'Missouri',
  MS: 'Mississippi',
  MT: 'Montana',
  NC: 'North Carolina',
  ND: 'North Dakota',
  NE: 'Nebraska',
  NH: 'New Hampshire',
  NJ: 'New Jersey',
  NM: 'New Mexico',
  NV: 'Nevada',
  NY: 'New York',
  OH: 'Ohio',
  OK: 'Oklahoma',
  OR: 'Oregon',
  PA: 'Pennsylvania',
  PR: 'Puerto Rico',
  RI: 'Rhode Island',
  SC: 'South Carolina',
  SD: 'South Dakota',
  TN: 'Tennessee',
  TX: 'Texas',
  UT: 'Utah',
  VA: 'Virginia',
  VT: 'Vermont',
  WA: 'Washington',
  WI: 'Wisconsin',
  WV: 'West Virginia',
  WY: 'Wyoming',
};

export const industryIcons: Record<number, React.ReactNode> = {
  1: <CardTravel />, // 'Hospitality',
  3: <Fastfood />, // 'Food',
  5: <Construction />, // 'Construction',
  7: <AccountBalance />, // 'Financial Services',
  8: <MedicalServices />, // 'Medical',
  11: <PrecisionManufacturing />, // 'Manufacturing',
  13: <MiscellaneousServices />, // 'Miscellaneous',
  17: <Apartment />, // 'Real Estate',
  18: <PointOfSale />, // 'Retail',
  19: <Commute />, // 'Transportation',
  23: <Checkroom />, // 'Apparel',
  24: <Factory />, // 'Metals',
  25: <Chair />, // 'Furniture',
  26: <FilePresent />, // 'Paper and Packaging',
  27: <Science />, // 'Chemical',
  28: <LocalGasStation />, // 'Oil and Gas',
  29: <Computer />, // 'Technology',
  30: <BusinessCenter />, // 'Business Services',
};

export const allIndustries = ['all'];
