security:
- bearerAuth: []

tags:
  - watchlist
summary: add a bankruptcy to watchlist / notifications
description: must supply the dc_id for the bk to be added

requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          id:
            type: integer
            description: DC ID for BK

responses:
  204:
    description: Successful response
    content: {}
  400:
    description: Bad Request
    content: {}
  500:
    description: Internal Server Error
    content: {}
