security:
- bearerAuth: []

tags:
  - case
summary: refresh bankruptcy docket details
description: provide a dci_id to get a docket entry updates

parameters:
- name: dci_id
  in: query
  description: Return BK View Data for specific given IDs
  schema:
    type: integer
responses:
  200:
    description: Successful response
    content:
      application/json:
        schema:
          type: array
          items:
            type: object
  400:
    description: Bad Request
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
  500:
    description: Internal Server Error
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
