security:
- bearerAuth: []

tags:
  - user management
summary: update user password in Auth0
description: allows the user to perform password operations

requestBody:
  required: true
  content:
    application/x-www-form-urlencoded:
      schema:
        type: object
        properties:
          password:
            required: true
            type: string
            format: password
            description: New Password

responses:
  200:
    description: Successful response
    content: {}
  401:
    description: Unauthorized Request
    content: {}
  400:
    description: Bad Request
    content: {}
  500:
    description: Internal Server Error
    content: {}
