security:
- bearerAuth: []

tags:
  - watchlist
summary: remove a creditor from watchlist / notifications
description: must supply the loss ID for the company to be deleted

requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          id:
            type: integer
            description: loss ID

responses:
  204:
    description: Successful response
    content: {}
  400:
    description: Bad Request
    content: {}
  500:
    description: Internal Server Error
    content: {}
