security:
- bearerAuth: []

tags:
  - team management
summary: delete user in the database associated with a Team
description: supply the required parameters to create a team user

requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          member_email_address:
            required: true
            type: string
            description: Member Email Address
responses:
  204:
    description: Successful response
    content: {}
  400:
    description: Bad Request
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
  500:
    description: Internal Server Error
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
