security:
- bearerAuth: []

tags:
  - notifications
summary: mark notification read
description: marks the supplied notification ID as read

requestBody:
  required: true
  content:
    application/x-www-form-urlencoded:
      schema:
        type: object
        properties:
          id:
            required: false
            type: integer
            description: Notification status

responses:
  200:
    description: Successful response
    content: {}
  401:
    description: Unauthorized Request
    content: {}
  400:
    description: Bad Request
    content: {}
  500:
    description: Internal Server Error
    content: {}
