security:
- bearerAuth: []

tags:
  - user management
summary: update an existing user industry entries
description: supply list of industry id's to associate with account

requestBody:
  required: true
  content:
    application/x-www-form-urlencoded:
      schema:
        type: object
        properties:
          update_industries:
            type: array
            items:
              type: integer
responses:
  204:
    description: Successful response
    content: {}
  400:
    description: Bad Request
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
  500:
    description: Internal Server Error
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
